/*
	Microsoft Dynamics AX for Retail POS Upgrade Database Script
	DbVersion: 6.2.38.0
*/

IF NOT EXISTS (SELECT * FROM sys.columns WHERE [name] = N'SETTLEMENTACCOUNTINGOPTION' AND [object_id] = OBJECT_ID(N'[dbo].[TAXRTDOCCOMPPOSTINGPROFDETVERSION]'))
BEGIN
ALTER TABLE [dbo].[TAXRTDOCCOMPPOSTINGPROFDETVERSION] ADD [SETTLEMENTACCOUNTINGOPTION] [int] NOT NULL CONSTRAINT [DF_TAXRTDOCCOMPPOSTINGPROFDETVERSION_SETTLEMENTACCOUNTINGOPTION] DEFAULT ((0))
END
GO

-------------------------------------------------------------------------------

IF NOT EXISTS (SELECT * FROM sys.columns WHERE [name] = N'DESCRIPTION' AND [object_id] = OBJECT_ID(N'[dbo].[ERSOLUTIONTABLE]'))
BEGIN
ALTER TABLE [dbo].[ERSOLUTIONTABLE] ADD [DESCRIPTION] [nvarchar](60) NOT NULL CONSTRAINT [DF_ERSOLUTIONTABLE_DESCRIPTION] DEFAULT ((0))
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE [name] = N'SOLUTIONPROVIDER' AND [object_id] = OBJECT_ID(N'[dbo].[ERSOLUTIONTABLE]'))
BEGIN
ALTER TABLE [dbo].[ERSOLUTIONTABLE] ADD [SOLUTIONPROVIDER] [nvarchar](60) NOT NULL CONSTRAINT [DF_ERSOLUTIONTABLE_SOLUTIONPROVIDER] DEFAULT ((0))
END
GO

-------------------------------------------------------------------------------

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TAXDOCUMENTJSON]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[TAXDOCUMENTJSON](
	[RECID] [bigint] NOT NULL,
	[ID] [uniqueidentifier] NOT NULL,
	[JSON] [nvarchar](max) NULL,
 CONSTRAINT [I_TAXDOCUMENTJSON_RECID] PRIMARY KEY CLUSTERED 
(
	[RECID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [I_TAXDOCUMENTJSON_IDX] UNIQUE NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE [name] = N'RECID' AND [object_id] = OBJECT_ID(N'[dbo].[TAXDOCUMENTJSON]'))
BEGIN
ALTER TABLE [dbo].[TAXDOCUMENTJSON] ADD [RECID] [bigint] NOT NULL CONSTRAINT [DF_TAXDOCUMENTJSON_RECID] DEFAULT ((0))
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE [name] = N'ID' AND [object_id] = OBJECT_ID(N'[dbo].[TAXDOCUMENTJSON]'))
BEGIN
ALTER TABLE [dbo].[TAXDOCUMENTJSON] ADD [ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF_TAXDOCUMENTJSON_ID] DEFAULT ('{00000000-0000-0000-0000-000000000000}')
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE [name] = N'JSON' AND [object_id] = OBJECT_ID(N'[dbo].[TAXDOCUMENTJSON]'))
BEGIN
ALTER TABLE [dbo].[TAXDOCUMENTJSON] ADD [JSON] [nvarchar](60) NOT NULL CONSTRAINT [DF_TAXDOCUMENTJSON_JSON] DEFAULT ('')
END
GO

-------------------------------------------------------------------------------

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TAXDOCUMENTROWMEASUREADJUSTMENT]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[TAXDOCUMENTROWMEASUREADJUSTMENT](
	[RECID] [bigint] NOT NULL,
	[ADJUSTAMOUNT] [numeric](32, 16) NOT NULL,
	[ADJUSTAMOUNT_ACCCUR] [numeric](32, 16) NOT NULL,
	[ADJUSTAMOUNT_TRANS] [numeric](32, 16) NOT NULL,
	[PATH] [nvarchar](300) NOT NULL,
	[SOURCERECID] [bigint] NOT NULL,
	[SOURCETABLEID] [int] NOT NULL,
 CONSTRAINT [I_TAXDOCUMENTROWMEASUREADJUSTMENT_RECID] PRIMARY KEY CLUSTERED 
(
	[RECID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [I_TAXDOCUMENTROWMEASUREADJUSTMENT_MEASUREIDX] UNIQUE NONCLUSTERED 
(
	[SOURCETABLEID] ASC,
	[SOURCERECID] ASC,
	[PATH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE [name] = N'RECID' AND [object_id] = OBJECT_ID(N'[dbo].[TAXDOCUMENTROWMEASUREADJUSTMENT]'))
BEGIN
ALTER TABLE [dbo].[TAXDOCUMENTROWMEASUREADJUSTMENT] ADD [RECID] [bigint] NOT NULL CONSTRAINT [DF_TAXDOCUMENTROWMEASUREADJUSTMENT_RECID] DEFAULT ((0))
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE [name] = N'ADJUSTAMOUNT' AND [object_id] = OBJECT_ID(N'[dbo].[TAXDOCUMENTROWMEASUREADJUSTMENT]'))
BEGIN
ALTER TABLE [dbo].[TAXDOCUMENTROWMEASUREADJUSTMENT] ADD [ADJUSTAMOUNT] [numeric](32, 16) NOT NULL CONSTRAINT [DF_TAXDOCUMENTROWMEASUREADJUSTMENT_ADJUSTAMOUNT] DEFAULT ((0))
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE [name] = N'ADJUSTAMOUNT_ACCCUR' AND [object_id] = OBJECT_ID(N'[dbo].[TAXDOCUMENTROWMEASUREADJUSTMENT]'))
BEGIN
ALTER TABLE [dbo].[TAXDOCUMENTROWMEASUREADJUSTMENT] ADD [ADJUSTAMOUNT_ACCCUR] [numeric](32, 16) NOT NULL CONSTRAINT [DF_TAXDOCUMENTROWMEASUREADJUSTMENT_ADJUSTAMOUNT_ACCCUR] DEFAULT ((0))
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE [name] = N'ADJUSTAMOUNT_TRANS' AND [object_id] = OBJECT_ID(N'[dbo].[TAXDOCUMENTROWMEASUREADJUSTMENT]'))
BEGIN
ALTER TABLE [dbo].[TAXDOCUMENTROWMEASUREADJUSTMENT] ADD [ADJUSTAMOUNT_TRANS] [numeric](32, 16) NOT NULL CONSTRAINT [DF_TAXDOCUMENTROWMEASUREADJUSTMENT_ADJUSTAMOUNT_TRANS] DEFAULT ((0))
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE [name] = N'PATH' AND [object_id] = OBJECT_ID(N'[dbo].[TAXDOCUMENTROWMEASUREADJUSTMENT]'))
BEGIN
ALTER TABLE [dbo].[TAXDOCUMENTROWMEASUREADJUSTMENT] ADD [PATH] [nvarchar](300) NOT NULL CONSTRAINT [DF_TAXDOCUMENTROWMEASUREADJUSTMENT_PATH] DEFAULT ((0))
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE [name] = N'SOURCERECID' AND [object_id] = OBJECT_ID(N'[dbo].[TAXDOCUMENTROWMEASUREADJUSTMENT]'))
BEGIN
ALTER TABLE [dbo].[TAXDOCUMENTROWMEASUREADJUSTMENT] ADD [SOURCERECID] [bigint] NOT NULL CONSTRAINT [DF_TAXDOCUMENTROWMEASUREADJUSTMENT_SOURCERECID] DEFAULT ((0))
END

IF NOT EXISTS (SELECT * FROM sys.columns WHERE [name] = N'SOURCETABLEID' AND [object_id] = OBJECT_ID(N'[dbo].[TAXDOCUMENTROWMEASUREADJUSTMENT]'))
BEGIN
ALTER TABLE [dbo].[TAXDOCUMENTROWMEASUREADJUSTMENT] ADD [SOURCETABLEID] [int] NOT NULL CONSTRAINT [DF_TAXDOCUMENTROWMEASUREADJUSTMENT_SOURCETABLEID] DEFAULT ((0))
END
GO