/*
	Microsoft Dynamics AX for Retail POS Upgrade Database Script
	DbVersion: 6.2.33.0
*/

DROP INDEX [I_1213BARCODEIDX] ON [dbo].[INVENTITEMBARCODE]
GO

CREATE NONCLUSTERED INDEX [I_1213BARCODEIDX] ON [dbo].[INVENTITEMBARCODE]
(
	[DATAAREAID] ASC,
	[ITEMBARCODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

