/*
	Microsoft Dynamics AX for Retail POS Upgrade Database Script
	DbVersion: 6.2.20.0
*/

/****** adding new column to [RETAILPARAMETERS] to initialize payment refund amount with available for current tender type amount for Russia ******/
ALTER TABLE [dbo].[RETAILPARAMETERS]
ADD 
	[PROPOSEREFUNDPAYMENTAMOUNT_RU] [int] NOT NULL DEFAULT (0)
GO

/****** adding columns to [RETAILPOSPERMISSIONGROUP] and [RETAILPOSITIONPOSPERMISSION] tables to control the permission to perform refunds in tender types different from the ones osed in the original transaction ******/
ALTER TABLE [dbo].[RETAILPOSPERMISSIONGROUP]
ADD
	[ALLOWDIFFERENTPAYMENTMETHODREFUNDS_RU] [int] NOT NULL DEFAULT(0)
GO

ALTER TABLE [dbo].[RETAILPOSITIONPOSPERMISSION]
ADD
	[ALLOWDIFFERENTPAYMENTMETHODREFUNDS_RU] [int] NOT NULL DEFAULT(0)
GO

/****** create [dbo].[RETAILTRANSACTIONRETURNENTRYSUM] table for storing refunds grouped by entry types and ids for the transaction ******/
CREATE TABLE [dbo].[RETAILTRANSACTIONRETURNENTRYSUM](
	[DATAAREAID] [nvarchar](4) NOT NULL,
	[STORE] [nvarchar](10) NOT NULL,
	[TERMINAL] [nvarchar](10) NOT NULL,
	[TRANSACTIONID] [nvarchar](44) NOT NULL,
	[ENTRYTYPE] [int] NOT NULL,
	[ENTRYID] [nvarchar](10) NOT NULL,
	[ISLOYALTYPAYMENT] [bit] NOT NULL,
	[AMOUNT] [numeric](32, 16) NOT NULL,
 CONSTRAINT [PK_RETAILTRANSACTIONRETURNENTRYSUM] PRIMARY KEY CLUSTERED 
(
	[DATAAREAID] ASC,
	[STORE] ASC,
	[TERMINAL] ASC,
	[TRANSACTIONID] ASC,
	[ENTRYTYPE] ASC,
	[ENTRYID] ASC,
	[ISLOYALTYPAYMENT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[RETAILTRANSACTIONRETURNENTRYSUM] ADD  CONSTRAINT [DF_RETAILTRANSACTIONRETURNENTRYSUM_TRANSACTIONID]  DEFAULT ('') FOR [TRANSACTIONID]
GO

ALTER TABLE [dbo].[RETAILTRANSACTIONRETURNENTRYSUM] ADD  CONSTRAINT [DF_RETAILTRANSACTIONRETURNENTRYSUM_STORE]  DEFAULT ('') FOR [STORE]
GO

ALTER TABLE [dbo].[RETAILTRANSACTIONRETURNENTRYSUM] ADD  CONSTRAINT [DF_RETAILTRANSACTIONRETURNENTRYSUM_TERMINAL]  DEFAULT ('') FOR [TERMINAL]
GO

ALTER TABLE [dbo].[RETAILTRANSACTIONRETURNENTRYSUM] ADD  CONSTRAINT [DF_RETAILTRANSACTIONRETURNENTRYSUM_DATAAREAID]  DEFAULT ('') FOR [DATAAREAID]
GO

ALTER TABLE [dbo].[RETAILTRANSACTIONRETURNENTRYSUM] ADD  CONSTRAINT [DF_RETAILTRANSACTIONRETURNENTRYSUM_ISLOYALTYPAYMENT]  DEFAULT ((0)) FOR [ISLOYALTYPAYMENT]
GO

ALTER TABLE [dbo].[RETAILTRANSACTIONRETURNENTRYSUM] ADD  CONSTRAINT [DF_RETAILTRANSACTIONRETURNENTRYSUM_ENTRYTYPE]  DEFAULT ((0)) FOR [ENTRYTYPE]
GO

ALTER TABLE [dbo].[RETAILTRANSACTIONRETURNENTRYSUM] ADD  CONSTRAINT [DF_RETAILTRANSACTIONRETURNENTRYSUM_ENTRYID]  DEFAULT ('') FOR [ENTRYID]
GO
