/*
    Microsoft Dynamics AX for Retail POS Upgrade Database Script
    DbVersion: 6.2.29.0
*/

ALTER FUNCTION [dbo].[GETPARTYPRIMARYADDRESS]
(
@PARTYID		BIGINT
)
RETURNS NVARCHAR(255)
AS
BEGIN
DECLARE @ADDRESS	NVARCHAR(255)

SET @ADDRESS = (SELECT TOP 1 REPLACE(LPA.[ADDRESS], CHAR(10), ' ')
FROM DIRPARTYTABLE PT
INNER JOIN DIRPARTYLOCATION	PL
ON PT.RECID = PL.PARTY
AND
PL.ISPOSTALADDRESS = 1
AND
PL.ISPRIMARY = 1
AND
PL.ISPRIVATE = 0
AND
PL.VALIDFROM <= GETUTCDATE() AND PL.VALIDTO >= GETUTCDATE()
INNER JOIN	LOGISTICSPOSTALADDRESS LPA
ON PL.LOCATION = LPA.LOCATION
AND 
LPA.VALIDFROM <= GETUTCDATE() AND LPA.VALIDTO >= GETUTCDATE()
WHERE
PT.RECID = @PARTYID)

RETURN @ADDRESS

END
GO

