/*
	Microsoft Dynamics AX for Retail POS Upgrade Database Script
	DbVersion: 6.2.15.0
*/


ALTER TABLE RETAILPOSPERMISSIONGROUP
ADD

   ALLOWPASSWORDCHANGE [INT] NOT NULL CONSTRAINT AllowPasswordChangeRPPGDefault DEFAULT (0) WITH VALUES,
   ALLOWRESETPASSWORD [INT] NOT NULL CONSTRAINT AllowResetPasswordRPPGDefault DEFAULT (0) WITH VALUES
GO


ALTER TABLE RETAILPARAMETERS
ADD
     REQUIRESPECIALCHAR [INT] NOT NULL CONSTRAINT AddSpecialCharDefault DEFAULT (0) WITH VALUES,
	 REQUIREUPPERCASE [INT] NOT NULL CONSTRAINT AddUpperCaseDefault DEFAULT (0) WITH VALUES,
	 REQUIRENUMERICCHAR [INT] NOT NULL CONSTRAINT AddNumericCharDefault DEFAULT (0) WITH VALUES,
	 MINIMUMPASSWORDLENGTH [INT] NOT NULL CONSTRAINT AddPasswordLengthDefault DEFAULT (0) WITH VALUES

  
GO

ALTER TABLE RETAILPOSITIONPOSPERMISSION
ADD

   ALLOWPASSWORDCHANGE [INT] NOT NULL CONSTRAINT AllowPasswordChangeRPPPDefault DEFAULT (0) WITH VALUES,
   ALLOWRESETPASSWORD [INT] NOT NULL CONSTRAINT AllowResetPasswordRPPPDefault DEFAULT (0) WITH VALUES
GO

ALTER TABLE RETAILFUNCTIONALITYPROFILE
ADD
    NOSALE NVARCHAR(10)
GO
