/*
	Microsoft Dynamics AX for Retail POS Upgrade Database Script
	DbVersion: 6.2.24.0
*/


DROP FUNCTION [dbo].[GETPARTYPRIMARYCONTACT]
GO


/****** Object:  UserDefinedFunction [dbo].[GETPARTYPRIMARYCONTACT]  ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [dbo].[GETPARTYPRIMARYCONTACT]
(
@PARTYID		BIGINT,
@CONTACTTYPE	INT
)
RETURNS NVARCHAR(255)
AS
BEGIN

DECLARE @LOCATOR		NVARCHAR(255)

SET @LOCATOR = (SELECT TOP 1 LEA.LOCATOR
FROM DIRPARTYTABLE PT
INNER JOIN DIRPARTYLOCATION PL
ON PT.RECID = PL.PARTY
AND
PL.ISPOSTALADDRESS = 0
AND
PL.ISPRIVATE = 0
INNER JOIN LOGISTICSELECTRONICADDRESS LEA
ON PL.LOCATION = LEA.LOCATION
AND
LEA.ISPRIMARY = 1
AND
LEA.VALIDFROM <= GETUTCDATE() AND LEA.VALIDTO >= GETUTCDATE()
AND
LEA.TYPE = @CONTACTTYPE
WHERE
PT.RECID = @PARTYID)

RETURN @LOCATOR

END

GO