/*
	Microsoft Dynamics AX for Retail POS Upgrade Database Script
	DbVersion: 6.2.13.0
*/

/*
 * Adding table [RETAILCONFIGURATION_BR]
 */

CREATE TABLE [dbo].[RETAILCONFIGURATION_BR](
	[RECID] [bigint] NOT NULL,
	[VALUE] [nvarchar](20) NOT NULL DEFAULT(''),
	[TYPE] [int] NOT NULL DEFAULT(0),
	[PURPOSE] [int] NOT NULL DEFAULT(0),
 CONSTRAINT [PK_RETAILCONFIGURATION] PRIMARY KEY CLUSTERED 
(
	[RECID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/*
 * Adding table [RETAILCONFIGURATION_BR]
 */

CREATE TABLE [dbo].[RETAILCONFIGURATIONSTORETABLE_BR](
	[RECID] [bigint] NOT NULL,
	[RETAILCONFIGURATION_BR] [bigint] NOT NULL,
	[RETAILSTORETABLE] [bigint] NOT NULL,
	CONSTRAINT [PK_RETAILCONFIGURATIONSTORETABLE_BR] PRIMARY KEY CLUSTERED 
	(
		[RECID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

-- [Section: Brazilian transaction tables index fix]
-- The following transaction (P-job) tables should have these changes:
--   1. drop the original incorrect clustered index
--   2. create clustered index on REPLICATIONCOUNTER field
--   3. add back original primary key as non-clustered index

-- RETAILCARDPAYMENT_BR
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[RETAILCARDPAYMENT_BR]') AND name = N'PK_RETAILCARDPAYMENT_BR')
ALTER TABLE [dbo].[RETAILCARDPAYMENT_BR] DROP CONSTRAINT [PK_RETAILCARDPAYMENT_BR]
GO

CREATE CLUSTERED INDEX [I_REPLICATIONCOUNTERIDX] ON [dbo].[RETAILCARDPAYMENT_BR]
(
	[REPLICATIONCOUNTER] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RETAILCARDPAYMENT_BR] ADD  CONSTRAINT [PK_RETAILCARDPAYMENT_BR] PRIMARY KEY NONCLUSTERED 
(
	[DATAAREAID] ASC,
	[STOREID] ASC,
	[TERMINALID] ASC,
	[TRANSACTIONID] ASC,
	[CONTROLNUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

-- RETAILFISCALDOCUMENTMODEL2_BR
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[RETAILFISCALDOCUMENTMODEL2_BR]') AND name = N'PK_RETAILFISCALDOCUMENTMODEL2_BR')
ALTER TABLE [dbo].[RETAILFISCALDOCUMENTMODEL2_BR] DROP CONSTRAINT [PK_RETAILFISCALDOCUMENTMODEL2_BR]
GO

CREATE CLUSTERED INDEX [I_REPLICATIONCOUNTERIDX] ON [dbo].[RETAILFISCALDOCUMENTMODEL2_BR]
(
	[REPLICATIONCOUNTER] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RETAILFISCALDOCUMENTMODEL2_BR] ADD  CONSTRAINT [PK_RETAILFISCALDOCUMENTMODEL2_BR] PRIMARY KEY NONCLUSTERED 
(
	[FISCALDOCUMENTNUMBER] ASC,
	[FISCALDOCUMENTSERIES] ASC,
	[FISCALDOCUMENTDATE] ASC,
	[TERMINALID] ASC,
	[STOREID] ASC,
	[DATAAREAID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

-- RETAILFISCALDOCUMENTMODEL2LINE_BR
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[RETAILFISCALDOCUMENTMODEL2LINE_BR]') AND name = N'PK_RETAILFISCALDOCUMENTMODEL2LINE_BR')
ALTER TABLE [dbo].[RETAILFISCALDOCUMENTMODEL2LINE_BR] DROP CONSTRAINT [PK_RETAILFISCALDOCUMENTMODEL2LINE_BR]
GO

CREATE CLUSTERED INDEX [I_REPLICATIONCOUNTERIDX] ON [dbo].[RETAILFISCALDOCUMENTMODEL2LINE_BR]
(
	[REPLICATIONCOUNTER] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RETAILFISCALDOCUMENTMODEL2LINE_BR] ADD  CONSTRAINT [PK_RETAILFISCALDOCUMENTMODEL2LINE_BR] PRIMARY KEY NONCLUSTERED 
(
	[LINENUM] ASC,
	[TRANSACTIONID] ASC,
	[TERMINALID] ASC,
	[STOREID] ASC,
	[DATAAREAID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

-- RETAILFISCALDOCUMENTMODEL2TAXTRANS_BR
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[RETAILFISCALDOCUMENTMODEL2TAXTRANS_BR]') AND name = N'PK_RETAILFISCALDOCUMENTMODEL2TAXTRANS_BR')
ALTER TABLE [dbo].[RETAILFISCALDOCUMENTMODEL2TAXTRANS_BR] DROP CONSTRAINT [PK_RETAILFISCALDOCUMENTMODEL2TAXTRANS_BR]
GO

CREATE CLUSTERED INDEX [I_REPLICATIONCOUNTERIDX] ON [dbo].[RETAILFISCALDOCUMENTMODEL2TAXTRANS_BR]
(
	[REPLICATIONCOUNTER] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RETAILFISCALDOCUMENTMODEL2TAXTRANS_BR] ADD  CONSTRAINT [PK_RETAILFISCALDOCUMENTMODEL2TAXTRANS_BR] PRIMARY KEY NONCLUSTERED 
(
	[TAXTYPE] ASC,
	[LINENUM] ASC,
	[TRANSACTIONID] ASC,
	[TERMINALID] ASC,
	[STOREID] ASC,
	[DATAAREAID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

-- RETAILFISCALPRINTER_BR
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[RETAILFISCALPRINTER_BR]') AND name = N'PK_RETAILFISCALPRINTER_BR')
ALTER TABLE [dbo].[RETAILFISCALPRINTER_BR] DROP CONSTRAINT [PK_RETAILFISCALPRINTER_BR]
GO

CREATE CLUSTERED INDEX [I_REPLICATIONCOUNTERIDX] ON [dbo].[RETAILFISCALPRINTER_BR]
(
	[REPLICATIONCOUNTER] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RETAILFISCALPRINTER_BR] ADD  CONSTRAINT [PK_RETAILFISCALPRINTER_BR] PRIMARY KEY NONCLUSTERED 
(
	[RESTARTOPERATIONNUMBER] ASC,
	[ADDITIONALFISCALMEMORYINDEX] ASC,
	[SERIALNUMBER] ASC,
	[TERMINALID] ASC,
	[STOREID] ASC,
	[DATAAREAID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

-- RETAILFISCALPRINTERREPORT_BR
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[RETAILFISCALPRINTERREPORT_BR]') AND name = N'PK_RETAILFISCALPRINTERREPORT_BR')
ALTER TABLE [dbo].[RETAILFISCALPRINTERREPORT_BR] DROP CONSTRAINT [PK_RETAILFISCALPRINTERREPORT_BR]
GO

CREATE CLUSTERED INDEX [I_REPLICATIONCOUNTERIDX] ON [dbo].[RETAILFISCALPRINTERREPORT_BR]
(
	[REPLICATIONCOUNTER] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RETAILFISCALPRINTERREPORT_BR] ADD  CONSTRAINT [PK_RETAILFISCALPRINTERREPORT_BR] PRIMARY KEY NONCLUSTERED 
(
	[RESTARTOPERATIONNUMBER] ASC,
	[RECEIPTNUMBER] ASC,
	[ADDITIONALFISCALMEMORYINDEX] ASC,
	[FISCALPRINTERSERIALNUMBER] ASC,
	[TERMINALID] ASC,
	[STOREID] ASC,
	[DATAAREAID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

-- RETAILFISCALRECEIPT_BR
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[RETAILFISCALRECEIPT_BR]') AND name = N'PK_RETAILFISCALRECEIPT_BR')
ALTER TABLE [dbo].[RETAILFISCALRECEIPT_BR] DROP CONSTRAINT [PK_RETAILFISCALRECEIPT_BR]
GO

CREATE CLUSTERED INDEX [I_REPLICATIONCOUNTERIDX] ON [dbo].[RETAILFISCALRECEIPT_BR]
(
	[REPLICATIONCOUNTER] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RETAILFISCALRECEIPT_BR] ADD  CONSTRAINT [PK_RETAILFISCALRECEIPT_BR] PRIMARY KEY NONCLUSTERED 
(
	[TRANSACTIONID] ASC,
	[TERMINALID] ASC,
	[STOREID] ASC,
	[DATAAREAID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

-- RETAILFISCALRECEIPTLINE_BR
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[RETAILFISCALRECEIPTLINE_BR]') AND name = N'PK_RETAILFISCALRECEIPTLINE_BR')
ALTER TABLE [dbo].[RETAILFISCALRECEIPTLINE_BR] DROP CONSTRAINT [PK_RETAILFISCALRECEIPTLINE_BR]
GO

CREATE CLUSTERED INDEX [I_REPLICATIONCOUNTERIDX] ON [dbo].[RETAILFISCALRECEIPTLINE_BR]
(
	[REPLICATIONCOUNTER] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RETAILFISCALRECEIPTLINE_BR] ADD  CONSTRAINT [PK_RETAILFISCALRECEIPTLINE_BR] PRIMARY KEY NONCLUSTERED 
(
	[LINENUM] ASC,
	[TRANSACTIONID] ASC,
	[TERMINALID] ASC,
	[STOREID] ASC,
	[DATAAREAID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

-- RETAILFISCALRECEIPTTAXTRANS_BR
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[RETAILFISCALRECEIPTTAXTRANS_BR]') AND name = N'PK_RETAILFISCALRECEIPTTAXTRANS_BR')
ALTER TABLE [dbo].[RETAILFISCALRECEIPTTAXTRANS_BR] DROP CONSTRAINT [PK_RETAILFISCALRECEIPTTAXTRANS_BR]
GO

CREATE CLUSTERED INDEX [I_REPLICATIONCOUNTERIDX] ON [dbo].[RETAILFISCALRECEIPTTAXTRANS_BR]
(
	[REPLICATIONCOUNTER] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RETAILFISCALRECEIPTTAXTRANS_BR] ADD  CONSTRAINT [PK_RETAILFISCALRECEIPTTAXTRANS_BR] PRIMARY KEY NONCLUSTERED 
(
	[TAXTYPE] ASC,
	[LINENUM] ASC,
	[TRANSACTIONID] ASC,
	[TERMINALID] ASC,
	[STOREID] ASC,
	[DATAAREAID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

-- RETAILTRANSACTIONPAYMENTTRANS_BR
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[RETAILTRANSACTIONPAYMENTTRANS_BR]') AND name = N'PK_RETAILTRANSACTIONPAYMENTTRANS_BR')
ALTER TABLE [dbo].[RETAILTRANSACTIONPAYMENTTRANS_BR] DROP CONSTRAINT [PK_RETAILTRANSACTIONPAYMENTTRANS_BR]
GO

CREATE CLUSTERED INDEX [I_REPLICATIONCOUNTERIDX] ON [dbo].[RETAILTRANSACTIONPAYMENTTRANS_BR]
(
	[REPLICATIONCOUNTER] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RETAILTRANSACTIONPAYMENTTRANS_BR] ADD  CONSTRAINT [PK_RETAILTRANSACTIONPAYMENTTRANS_BR] PRIMARY KEY NONCLUSTERED 
(
	[LINENUM] ASC,
	[TRANSACTIONID] ASC,
	[TERMINALID] ASC,
	[STOREID] ASC,
	[DATAAREAID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

-- RETAILZREPORT_BR
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[RETAILZREPORT_BR]') AND name = N'PK_RETAILZREPORT_BR')
ALTER TABLE [dbo].[RETAILZREPORT_BR] DROP CONSTRAINT [PK_RETAILZREPORT_BR]
GO

CREATE CLUSTERED INDEX [I_REPLICATIONCOUNTERIDX] ON [dbo].[RETAILZREPORT_BR]
(
	[REPLICATIONCOUNTER] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RETAILZREPORT_BR] ADD  CONSTRAINT [PK_RETAILZREPORT_BR] PRIMARY KEY NONCLUSTERED 
(
	[RESTARTOPERATIONNUMBER] ASC,
	[ZREPORTNUMBER] ASC,
	[ADDITIONALFISCALMEMORYINDEX] ASC,
	[FISCALPRINTERSERIALNUMBER] ASC,
	[TERMINALID] ASC,
	[STOREID] ASC,
	[DATAAREAID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

-- RETAILZREPORTTOTALIZER_BR
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[RETAILZREPORTTOTALIZER_BR]') AND name = N'PK_RETAILZREPORTTOTALIZER_BR')
ALTER TABLE [dbo].[RETAILZREPORTTOTALIZER_BR] DROP CONSTRAINT [PK_RETAILZREPORTTOTALIZER_BR]
GO

CREATE CLUSTERED INDEX [I_REPLICATIONCOUNTERIDX] ON [dbo].[RETAILZREPORTTOTALIZER_BR]
(
	[REPLICATIONCOUNTER] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RETAILZREPORTTOTALIZER_BR] ADD  CONSTRAINT [PK_RETAILZREPORTTOTALIZER_BR] PRIMARY KEY NONCLUSTERED 
(
	[FISCALPRINTERSERIALNUMBER] ASC,
	[TOTALIZERNAME] ASC,
	[ZREPORTNUMBER] ASC,
	[ADDITIONALFISCALMEMORYINDEX] ASC,
	[TERMINALID] ASC,
	[STOREID] ASC,
	[DATAAREAID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
