/*
	Microsoft Dynamics AX for Retail POS Upgrade Database Script
	DbVersion: 6.2.15.0
*/


/****** adding new column to [RETAILPERIODICDISCOUNT] for Russia ******/
ALTER TABLE [dbo].[RETAILPERIODICDISCOUNT]
ADD 
	[LOYALTYCARDREQUIRED_RU] [int] NOT NULL DEFAULT ((0)),
	[LOYALTYSCHEMEID_RU] [nvarchar](10) NOT NULL  DEFAULT (('')),
	[LOYALTYPOINTSMIN_RU] [numeric](32, 16) NOT NULL  DEFAULT ((0)),
	[LOYALTYPOINTSMAX_RU] [numeric](32, 16) NOT NULL  DEFAULT ((0))
GO




/****** recreating [RETAILPERIODICDISCOUNTSFLATTENED] view with new columns for Russia ******/
DROP VIEW [dbo].[RETAILPERIODICDISCOUNTSFLATTENED]
GO

CREATE VIEW [dbo].[RETAILPERIODICDISCOUNTSFLATTENED]
AS	
SELECT pd.[OFFERID], pd.[NAME], pd.[PERIODICDISCOUNTTYPE], pd.[PRICEDISCGROUP], 
		pd.[VALIDATIONPERIODID], pd.[DATEVALIDATIONTYPE], pd.[VALIDFROM], pd.[VALIDTO], 
		pd.[CONCURRENCYMODE], pd.[CURRENCYCODE], pd.[STATUS], pd.[ISDISCOUNTCODEREQUIRED],
		pd.LOYALTYCARDREQUIRED_RU, pd.LOYALTYSCHEMEID_RU, pd.LOYALTYPOINTSMIN_RU, pd.LOYALTYPOINTSMAX_RU,
		ISNULL(pdmm.MIXANDMATCHDISCOUNTTYPE, ISNULL(pdmb.MULTIBUYDISCOUNTTYPE, pd.PERIODICDISCOUNTTYPE)) as DISCOUNTTYPE, 
		0 as NOOFLINESTOTRIGGER, 
		pd.[DISCOUNTPERCENTVALUE],
		ISNULL(pdmm.[DEALPRICEVALUE],0.0) as DEALPRICEVALUE,
		ISNULL(pdmm.[DISCOUNTAMOUNTVALUE],0.0) as DISCOUNTAMOUNTVALUE, 
		ISNULL(pdmm.[NOOFLEASTEXPENSIVELINES],0) as NOOFLEASTEXPENSIVELINES, 
		ISNULL(pdmm.[NUMBEROFTIMESAPPLICABLE],0) as NUMBEROFTIMESAPPLICABLE,
		pdl.[RETAILGROUPMEMBERLINE], 
		pdl.[RECID] as DISCOUNTLINEID,
		pdl.[LINENUM], 
		pdl.[DISCOUNTPERCENTORVALUE], 
		pdl.[UNITOFMEASURE], 
		pd.[DATAAREAID]
FROM [dbo].[RETAILPERIODICDISCOUNT] as pd
JOIN [dbo].[RETAILPERIODICDISCOUNTLINE] as pdl ON pd.OFFERID = pdl.OFFERID AND pd.DATAAREAID = pdl.DATAAREAID
LEFT OUTER JOIN [dbo].[RETAILDISCOUNTMIXANDMATCH] as pdmm ON pd.RECID = pdmm.RECID
LEFT OUTER JOIN [dbo].[RETAILDISCOUNTMULTIBUY] as pdmb ON pd.RECID = pdmb.RECID
GO
