/*
	Microsoft Dynamics AX for Retail POS Upgrade Database Script
	DbVersion: 6.2.39.0
*/

IF NOT EXISTS (SELECT * FROM sys.columns WHERE [name] = N'DOCCONTEXTVERSION' AND [object_id] = OBJECT_ID(N'[dbo].[TAXRTLOOKUPSTRUCTFIELDCONDCOLUMNLINK]'))
BEGIN
ALTER TABLE [dbo].[TAXRTLOOKUPSTRUCTFIELDCONDCOLUMNLINK] ADD [DOCCONTEXTVERSION] [bigint] NOT NULL CONSTRAINT [DF_TAXRTLOOKUPSTRUCTFIELDCONDCOLUMNLINK_DOCCONTEXTVERSION] DEFAULT ((0))
END
GO

-------------------------------------------------------------------------------

IF NOT EXISTS (SELECT * FROM sys.columns WHERE [name] = N'TEMPLATEROWVERSION' AND [object_id] = OBJECT_ID(N'[dbo].[TAXRUNTIMEDOCMODELROWVERSION]'))
BEGIN
ALTER TABLE [dbo].[TAXRUNTIMEDOCMODELROWVERSION] ADD [TEMPLATEROWVERSION] [bigint] NOT NULL CONSTRAINT [DF_TAXRUNTIMEDOCMODELROWVERSION_TEMPLATEROWVERSION] DEFAULT ((0))
END
GO

-------------------------------------------------------------------------------

IF NOT EXISTS (SELECT * FROM sys.columns WHERE [name] = N'LOOKUPVERSION' AND [object_id] = OBJECT_ID(N'[dbo].[TAXRUNTIMELOOKUPCONDITION]'))
BEGIN
ALTER TABLE [dbo].[TAXRUNTIMELOOKUPCONDITION] ADD [LOOKUPVERSION] [bigint] NOT NULL CONSTRAINT [DF_TAXRUNTIMELOOKUPCONDITION_LOOKUPVERSION] DEFAULT ((0))
END
GO