/*
    Microsoft Dynamics AX for Retail POS Upgrade Database Script
    DbVersion: 6.2.27.0
*/

/****** Index created to enhance the search performance ******/
CREATE NONCLUSTERED INDEX [RETAILGROUPMEMBERLINE_VARPRODIDX] ON [dbo].[RETAILGROUPMEMBERLINE] 
(
	[VARIANT] ASC,
	[PRODUCT] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

