/*
	Microsoft Dynamics AX for Retail POS Upgrade Database Script
	DbVersion: 6.2.11.0
*/

/*
 * Update RETAILINVENTITEMSTOREORDERINGINFO table
 */
ALTER TABLE [dbo].RETAILINVENTITEMSTOREORDERINGINFO ALTER COLUMN [DISTRIBUTIONSUBGROUPID] nvarchar(50) NOT NULL
GO

/*
 * Update RETAILINVENTITEMLABELSETUP table
 */
ALTER TABLE [dbo].RETAILINVENTITEMLABELSETUP ALTER COLUMN [DISTRIBUTIONSUBGROUPID] nvarchar(50) NOT NULL
GO
