/*
	Microsoft Dynamics AX for Retail POS Upgrade Database Script
	DbVersion: 6.2.10.0
*/

/****** adding new table [RETAILTRANSACTIONTABLE_RU] for Russia to store fiscal memory data ******/
CREATE TABLE [dbo].[RETAILTRANSACTIONTABLE_RU](
	[CHANNEL] [bigint] NOT NULL DEFAULT ((0)),
	[STORE] [nvarchar](10) NOT NULL,
	[TERMINAL] [nvarchar](10) NOT NULL,
	[TRANSACTIONID] [nvarchar](44) NOT NULL,
	[REPLICATIONCOUNTER] [int] IDENTITY(1,1) NOT NULL,
	[KPKNUMBER] [nvarchar](8) NOT NULL DEFAULT (''),
	[FISCALDOCUMENTSERIALNUMBER] [nvarchar](10) NOT NULL DEFAULT (''),
	[EKLZSERIALNUMBER] [nvarchar](10) NOT NULL DEFAULT (''),
	[FISCALPRINTERSERIALNUMBER] [nvarchar](20) NOT NULL DEFAULT (''),
	[FISCALPRINTERSHIFTID] [nvarchar](5) NOT NULL DEFAULT (''),
	[DATAAREAID] [nvarchar](4) NOT NULL,			
 CONSTRAINT [TRANSACTION_IDX] PRIMARY KEY NONCLUSTERED 
 (
	[TRANSACTIONID] ASC,
	[STORE] ASC,
	[TERMINAL] ASC,
	[DATAAREAID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE CLUSTERED INDEX [I_REPLICATIONCOUNTERIDX] ON [dbo].[RETAILTRANSACTIONTABLE_RU]
(
	[REPLICATIONCOUNTER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

/****** adding FISCALPRINTER* columns to the RETAILHARDWAREPROFILE table for configuring fiscal printer settings ******/
ALTER TABLE [dbo].[RETAILHARDWAREPROFILE]
ADD
	[FISCALPRINTER] [int] NOT NULL DEFAULT((0)),
	[FISCALPRINTERDEVICENAME] [NVARCHAR](512) NOT NULL DEFAULT(''),
	[FISCALPRINTERDESCRIPTION] [NVARCHAR](60) NOT NULL DEFAULT('')
GO