/*
	Microsoft Dynamics AX for Retail POS Upgrade Database Script
	DbVersion: 6.2.26.0
*/

/****** Drop exisitng primary key and create a new primary key along with required additional columns******/

ALTER TABLE [dbo].[RETAILTRANSACTIONLOYALTYPOINTSTRANS] DROP CONSTRAINT [PK_RETAILTRANSACTIONLOYALTYPOINTSTRANS]
go

ALTER TABLE [dbo].[RETAILTRANSACTIONLOYALTYPOINTSTRANS] ADD  CONSTRAINT [PK_RETAILTRANSACTIONLOYALTYPOINTSTRANS] PRIMARY KEY NONCLUSTERED 
	(
		[TRANSACTIONID] ASC,
		[LINENUM] ASC,
		[STOREID] ASC,
		[TERMINALID] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

go




