/*
	Microsoft Dynamics AX for Retail POS Upgrade Database Script
	DbVersion: 6.2.21.0
*/

/****** adding trigger on ECORESPRODUCTTRANSLATION to track manual database changes for Brazil ******/
CREATE TRIGGER [dbo].[manualChanges_ECORESPRODUCTTRANSLATION]
	ON  [dbo].[ECORESPRODUCTTRANSLATION]
	AFTER INSERT, UPDATE, DELETE
AS
BEGIN
	DECLARE @APP NVARCHAR(128)

	DECLARE @RECIDINS BIGINT
	DECLARE @PRIMARYKEYINS NVARCHAR(200)

	DECLARE @RECIDDEL BIGINT
	DECLARE @PRIMARYKEYDEL NVARCHAR(200)

	SET NOCOUNT ON
	SET @APP = APP_NAME()
	IF (@APP <> 'Microsoft Dynamics AX for Retail POS') AND (@APP <> 'Retail Offline Sync Service')
	BEGIN
		-- delete
		IF EXISTS (SELECT * FROM deleted) AND NOT EXISTS (SELECT * FROM Inserted)
		BEGIN
			IF NOT EXISTS (SELECT * FROM [dbo].[RETAILMANUALCHANGESLOG_BR] WHERE TABLENAME = N'ECORESPRODUCTTRANSLATION' AND PRIMARYKEY = N'INSORDEL')
				INSERT INTO [dbo].[RETAILMANUALCHANGESLOG_BR] VALUES (N'ECORESPRODUCTTRANSLATION', N'INSORDEL', @APP)
		END
		ELSE
		-- Insert
		IF EXISTS (SELECT * FROM Inserted) AND NOT EXISTS (SELECT * FROM deleted)
		BEGIN
			IF NOT EXISTS (SELECT * FROM [dbo].[RETAILMANUALCHANGESLOG_BR] WHERE TABLENAME = N'ECORESPRODUCTTRANSLATION' AND PRIMARYKEY = N'INSORDEL')
				INSERT INTO [dbo].[RETAILMANUALCHANGESLOG_BR] VALUES (N'ECORESPRODUCTTRANSLATION', N'INSORDEL', @APP)

			DECLARE InsertedCursor CURSOR
				FOR SELECT RECID FROM Inserted
			OPEN InsertedCursor
			FETCH NEXT FROM InsertedCursor INTO @RECIDINS

			WHILE @@FETCH_STATUS = 0
			BEGIN
				SET @PRIMARYKEYINS = CONVERT(NVARCHAR, @RECIDINS)

				IF NOT EXISTS (SELECT * FROM [dbo].[RETAILMANUALCHANGESLOG_BR] WHERE TABLENAME = N'ECORESPRODUCTTRANSLATION' AND PRIMARYKEY = @PRIMARYKEYINS)
					INSERT INTO [dbo].[RETAILMANUALCHANGESLOG_BR] VALUES (N'ECORESPRODUCTTRANSLATION', @PRIMARYKEYINS, @APP)

				FETCH NEXT FROM InsertedCursor INTO @RECIDINS
			END

			CLOSE InsertedCursor
			DEALLOCATE InsertedCursor
		END
		ELSE
		-- update
		BEGIN
			DECLARE InsertedCursor CURSOR
				FOR SELECT RECID FROM Inserted
			OPEN InsertedCursor
			FETCH NEXT FROM InsertedCursor INTO @RECIDINS

			DECLARE deletedCursor CURSOR
				FOR SELECT RECID FROM deleted
			OPEN deletedCursor
			FETCH NEXT FROM deletedCursor INTO @RECIDDEL

			WHILE @@FETCH_STATUS = 0
			BEGIN
				SET @PRIMARYKEYINS = CONVERT(NVARCHAR, @RECIDINS)
				SET @PRIMARYKEYDEL = CONVERT(NVARCHAR, @RECIDDEL)

				IF NOT EXISTS (SELECT * FROM [dbo].[RETAILMANUALCHANGESLOG_BR] WHERE TABLENAME = N'ECORESPRODUCTTRANSLATION' AND PRIMARYKEY = @PRIMARYKEYDEL)
					INSERT INTO [dbo].[RETAILMANUALCHANGESLOG_BR] VALUES (N'ECORESPRODUCTTRANSLATION', @PRIMARYKEYINS, @APP)
				ELSE
					UPDATE [dbo].[RETAILMANUALCHANGESLOG_BR] SET PRIMARYKEY = @PRIMARYKEYINS WHERE TABLENAME = N'ECORESPRODUCTTRANSLATION' AND PRIMARYKEY = @PRIMARYKEYDEL

				FETCH NEXT FROM deletedCursor INTO @RECIDDEL
				FETCH NEXT FROM InsertedCursor INTO @RECIDINS
			END

			CLOSE deletedCursor
			DEALLOCATE deletedCursor

			CLOSE InsertedCursor
			DEALLOCATE InsertedCursor
		END
	END
END
GO


