//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Dynamics.Retail.FiscalPrinter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft.Dynamics.Retail.FiscalPrinter.PocokPrinter.dll")]
        public string FiscalPrinterAssembly_HU {
            get {
                return ((string)(this["FiscalPrinterAssembly_HU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft.Dynamics.Retail.FiscalPrinter.PocokPrinter.Pocok16Printer")]
        public string FiscalPrinterClass_HU {
            get {
                return ((string)(this["FiscalPrinterClass_HU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft.Dynamics.Retail.FiscalPrinter.DarumaPrinter.dll")]
        public string FiscalPrinterAssembly_BR {
            get {
                return ((string)(this["FiscalPrinterAssembly_BR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft.Dynamics.Retail.FiscalPrinter.DarumaPrinter.DarumaPrinter")]
        public string FiscalPrinterClass_BR {
            get {
                return ((string)(this["FiscalPrinterClass_BR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft.Dynamics.Retail.FiscalPrinter.ShtrihPrinter.dll")]
        public string FiscalPrinterAssembly_RU {
            get {
                return ((string)(this["FiscalPrinterAssembly_RU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft.Dynamics.Retail.FiscalPrinter.ShtrihPrinter.ShtrihPrinter")]
        public string FiscalPrinterClass_RU {
            get {
                return ((string)(this["FiscalPrinterClass_RU"]));
            }
        }
    }
}
